version: "3.8"

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    profiles:
      - mysql

  postgres:
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
    profiles:
      - postgres

  app-mysql:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    restart: on-failure
    environment:
      ACTIVE_PROFILE: mysql
    network_mode: host
    profiles:
      - mysql

  app-postgres:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    restart: on-failure
    environment:
      ACTIVE_PROFILE: postgres
    network_mode: host
    profiles:
      - postgres
