version: "2.2"

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
#    profiles:
#    - mysql
  postgres:
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
#    profiles:
#    - postgres

  app-mysql:
    image: maven:3.8.5-openjdk-17
    depends_on:
      - mysql
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8085:8085"
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
